### ISSUE TITLE
Switching from tree to array. Adding functions to parse and get attributes

### ISSUE THREAD

**Issue by TheAntiFlash** [TheAntiFlash/html-parser-with-kotlin#3]
After a few days of trying, we have decided that implementing a tree would be too difficult considering the short time slot we have. so we will be switching from tree to a simple MutableList<String,String>. Keeping that in mind, @osafahmed51 will be making functionality to get the attributes from a tag, while I @TheAntiFlash will be making a unction to get the tag from a string

**Comment by osafahmed51** [comment]
done
